// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAgentJWTTokenParams creates a new GetAgentJWTTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAgentJWTTokenParams() *GetAgentJWTTokenParams {
	return &GetAgentJWTTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAgentJWTTokenParamsWithTimeout creates a new GetAgentJWTTokenParams object
// with the ability to set a timeout on a request.
func NewGetAgentJWTTokenParamsWithTimeout(timeout time.Duration) *GetAgentJWTTokenParams {
	return &GetAgentJWTTokenParams{
		timeout: timeout,
	}
}

// NewGetAgentJWTTokenParamsWithContext creates a new GetAgentJWTTokenParams object
// with the ability to set a context for a request.
func NewGetAgentJWTTokenParamsWithContext(ctx context.Context) *GetAgentJWTTokenParams {
	return &GetAgentJWTTokenParams{
		Context: ctx,
	}
}

// NewGetAgentJWTTokenParamsWithHTTPClient creates a new GetAgentJWTTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAgentJWTTokenParamsWithHTTPClient(client *http.Client) *GetAgentJWTTokenParams {
	return &GetAgentJWTTokenParams{
		HTTPClient: client,
	}
}

/*
GetAgentJWTTokenParams contains all the parameters to send to the API endpoint

	for the get agent j w t token operation.

	Typically these are written to a http.Request.
*/
type GetAgentJWTTokenParams struct {

	/* AgentName.

	   Runner Name.
	*/
	AgentName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get agent j w t token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentJWTTokenParams) WithDefaults() *GetAgentJWTTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get agent j w t token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentJWTTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get agent j w t token params
func (o *GetAgentJWTTokenParams) WithTimeout(timeout time.Duration) *GetAgentJWTTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get agent j w t token params
func (o *GetAgentJWTTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get agent j w t token params
func (o *GetAgentJWTTokenParams) WithContext(ctx context.Context) *GetAgentJWTTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get agent j w t token params
func (o *GetAgentJWTTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get agent j w t token params
func (o *GetAgentJWTTokenParams) WithHTTPClient(client *http.Client) *GetAgentJWTTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get agent j w t token params
func (o *GetAgentJWTTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentName adds the agentName to the get agent j w t token params
func (o *GetAgentJWTTokenParams) WithAgentName(agentName string) *GetAgentJWTTokenParams {
	o.SetAgentName(agentName)
	return o
}

// SetAgentName adds the agentName to the get agent j w t token params
func (o *GetAgentJWTTokenParams) SetAgentName(agentName string) {
	o.AgentName = agentName
}

// WriteToRequest writes these params to a swagger request
func (o *GetAgentJWTTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agentName
	if err := r.SetPathParam("agentName", o.AgentName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
