// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// GetAgentJWTTokenReader is a Reader for the GetAgentJWTToken structure.
type GetAgentJWTTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentJWTTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentJWTTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAgentJWTTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /agent/{agentName}/token] GetAgentJWTToken", response, response.Code())
	}
}

// NewGetAgentJWTTokenOK creates a GetAgentJWTTokenOK with default headers values
func NewGetAgentJWTTokenOK() *GetAgentJWTTokenOK {
	return &GetAgentJWTTokenOK{}
}

/*
GetAgentJWTTokenOK describes a response with status code 200, with default header values.

JWTResponse
*/
type GetAgentJWTTokenOK struct {
	Payload garm_params.JWTResponse
}

// IsSuccess returns true when this get agent j w t token o k response has a 2xx status code
func (o *GetAgentJWTTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get agent j w t token o k response has a 3xx status code
func (o *GetAgentJWTTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent j w t token o k response has a 4xx status code
func (o *GetAgentJWTTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agent j w t token o k response has a 5xx status code
func (o *GetAgentJWTTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent j w t token o k response a status code equal to that given
func (o *GetAgentJWTTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get agent j w t token o k response
func (o *GetAgentJWTTokenOK) Code() int {
	return 200
}

func (o *GetAgentJWTTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/{agentName}/token][%d] getAgentJWTTokenOK %s", 200, payload)
}

func (o *GetAgentJWTTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/{agentName}/token][%d] getAgentJWTTokenOK %s", 200, payload)
}

func (o *GetAgentJWTTokenOK) GetPayload() garm_params.JWTResponse {
	return o.Payload
}

func (o *GetAgentJWTTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentJWTTokenUnauthorized creates a GetAgentJWTTokenUnauthorized with default headers values
func NewGetAgentJWTTokenUnauthorized() *GetAgentJWTTokenUnauthorized {
	return &GetAgentJWTTokenUnauthorized{}
}

/*
GetAgentJWTTokenUnauthorized describes a response with status code 401, with default header values.

APIErrorResponse
*/
type GetAgentJWTTokenUnauthorized struct {
	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this get agent j w t token unauthorized response has a 2xx status code
func (o *GetAgentJWTTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agent j w t token unauthorized response has a 3xx status code
func (o *GetAgentJWTTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent j w t token unauthorized response has a 4xx status code
func (o *GetAgentJWTTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agent j w t token unauthorized response has a 5xx status code
func (o *GetAgentJWTTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent j w t token unauthorized response a status code equal to that given
func (o *GetAgentJWTTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get agent j w t token unauthorized response
func (o *GetAgentJWTTokenUnauthorized) Code() int {
	return 401
}

func (o *GetAgentJWTTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/{agentName}/token][%d] getAgentJWTTokenUnauthorized %s", 401, payload)
}

func (o *GetAgentJWTTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/{agentName}/token][%d] getAgentJWTTokenUnauthorized %s", 401, payload)
}

func (o *GetAgentJWTTokenUnauthorized) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *GetAgentJWTTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
